### ISSUE TITLE
Implement delta packages

### ISSUE THREAD

**Issue by Tyrrrz** [Tyrrrz/Onova#1]

**Comment by Sewer56** [comment]
Hi there.

I've taken an interest to using this project, and although I've not yet had the chance of trying it out with a real project, the thought of adding delta support also came to mind. 

I was thinking of contributing, although with other things/projects on my plate, I'm not sure if I'll be able to do anything at the current time.

So at the very least, I want share some thoughts I had along the way myself regarding deltas.

--------------------------------------------

## File Delta Generation Libraries

| Algorithm | Option                 | Thoughts                                                                                                                                                                                         |
|-----------|------------------------|--------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------|
| bsdiff    | bsdiff.net             | No tests but known good implementation. No NuGet package so need to manually integrate. Used by Squirrel.                                                                                        |
| bsdiff    | deltaq                 | Minimal C# Implementation of bsdiff. Low level Abandoned? Has potential bug? (See issues)                                                                                                        |
| rsync     | Octodiff               | Commonly used and developed by developers of well known packaging/deployment software.                                                                                                           |
| rsync     | FastRsyncNet           | Derivative of Octodiff better than original?. Smaller signature sizes, faster to generate signatures (and thus deltas) due to hash algorithm change to xxHash. Supports asynchronous operations. |
| msdelta   | DeltaCompressionDotNet | ? I have no opinion of MSDelta.                                                                                                                                                                  |

All aforementioned libraries are MIT, MS-PL or Apache licensed.

I haven't had the chance to benchmark these against the each other yet and I can't seem to find any sets of comparative benchmarks outside of research papers that are more than 10 years old.
 
Based on initial analysis, for me the winner would be FastRsyncNet. 

That said, there is one thing I don't like about it. FastRsyncNet has a dependency on Newtonsoft.Json which is a whopping ~600KB (all other implementations have no extra dependencies). 

In nature, nothing is wrong with it but I am personally a fan of very small sized, extensible libraries, since with large libraries you often find that they are packed full of features when sometimes you need only one small thing.

## File Deletion/Exclusion
Sometimes in cases whereby you e.g. remove a dependency from the project,  you may find that in a new version of a package some files that previously existed do not exist.

I have thought of the following list of options.

| Option                                                                                                                                           | Thoughts                                                                                                                                                 |
|--------------------------------------------------------------------------------------------------------------------------------------------------|----------------------------------------------------------------------------------------------------------------------------------------------------------|
| Insert empty dummy files with an extra/suffix extension like `.del` and remove files matching name (without extension) in application directory. | Would require some extra code but does not sound unreasonable.                                                                                           |
| Only patch existing files, ignore files removed between deltas.                                                                                  | The commonplace implementation. True to the existing behaviour of the program.  Preferred choice but can leave redundant files in application directory. |
| No deltas where original list of files differs to new list of files.                                                                       | I don't like this idea.                                                                                                                                  |

Personally I prefer the second choice.

**Comment by Tyrrrz** [comment]
Hi,
Thanks for such a detailed analysis!

>That said, there is one thing I don't like about it. FastRsyncNet has a dependency on Newtonsoft.Json which is a whopping ~600KB (all other implementations have no extra dependencies).

Onova already takes dependency on Newtonsoft.Json because it does some JSON parsing in `GithubPackageResolver` and maybe other places.

As for file deletion, I also prefer the second choice.

Now, the main problem entailed by this feature is actually generating the diffs. Developers will want this to be a part of the CI/CD process and the diffs should be uploadable to their chosen provider.

The reason I was putting this off for very long is because currently the CI/CD integration is very smooth -- most projects already upload their binaries as releasable artifacts so all they have to do is configure Onova to find them. With diffs it will be quite a bit more complicated.

**Comment by Sewer56** [comment]
`Onova already takes dependency on Newtonsoft.Json`

Ahahahah, I actually didn't notice right until now and was about to change it. 
Did not expect that you would beat me to it in the dawn of morning.

I guess staying up all night is common amongst programmers.

**Comment by Sewer56** [comment]
Regarding the diffs, I agree that it is a difficult decision. 

I didn't initially look at it from the perspective of a CD/CI environment myself but I think the toughest part of the process would be actually determining the best course of action as to identifying whether a delta update is possible as opposed to actually generating the deltas.

Nonetheless, you probably already considered it but here is a simple idea for delta generation.

# Random Idea/Proposal for Delta Generation

Doing this in a CI/CD environment without any changes to the process (no additional scripts after build etc.) will probably be very difficult, if not impossible sadly. It may, however, be possible to come close to that.

In my opinion, the natural vector to have diffs work is to make a simple separate commandline application such as `Onova.Updater` (e.g. `Onova.Difftool`).

Said `Onova.Difftool` would allow for the specification of an IPackageResolver and IPackageExtractor as commandline parameters. Once executed, `Onova.Difftool` would then download the latest version according to the resolver and extractor and diff those, producing a file to be uploaded as an artifact by CI/CD process.

Such integration would be no more complex (in fact, much simpler) than integrating test coverage. As for getting the `Onova.Difftool` itself to be executed in the CI/CD process, these options come to mind:

| Option          | Thoughts                                                                                                                          |
|-----------------|-----------------------------------------------------------------------------------------------------------------------------------|
| Tyrrz.me        | Own site, own control of latest URL. So long as uploading the latest build isn't too annoying on your domain/site.                |
| Github Releases | Parse latest download from response of https://api.github.com/repos/Tyrrrz/Onova/releases/latest or simply pick specific version. |
| Chocolatey      | Commonly included in images of CI/CD solutions. Easy to create packages, super easy 1 line install in CI/CD.                      |

To make the process *even easier*, should pack `Onova` inside `Onova.Difftool` with [Costura.Fody](https://github.com/Fody/Costura) and have the user download a singular exe directly as opposed to extracting an archive.

## CI/CD Integration Example

Here's how including the idea in a CI/CD setup would look like.
Quite simply, it's two lines in any post build process.

### Downloading Difftool

#### Get Latest version from Github Releases (Example)
(Singular .exe packed with Costura)
```
// From gist: https://gist.github.com/steinwaywhw/a4cd19cda655b8249d908261a62687f8
curl -s https://api.github.com/repos/Tyrrrz/Onova/releases/latest \
| grep "browser_download_url.*exe" \
| cut -d : -f 2,3 \
| tr -d \" \
| wget -qi -
```

#### Get Specific version from Github Releases/Other Site (Example)
```
wget https://github.com/Tyrrrz/Onova/releases/download/2.5.0/Onova.Difftool.exe
```

### Running Difftool
```
./Onova.Difftool.exe --resolver GithubPackageResolver --GithubPackageResolver.RepositoryOwner Tyrrrz --GithubPackageResolver.RepositoryName OnovaTestRepo --GithubPackageResolver.AssetNamePattern *.onv 
```

## Potential Roadblocks

Dealing with different overloads for the resolvers may be difficult with commandline parameters.
Looking at the current resolvers, this would not be an issue, but perhaps down the road it is something to worth noting.

**Comment by Tyrrrz** [comment]
Again, what an amazing detailed analysis :)

One question, do you see `Onova.Difftool` as responsible also for uploading the diffs to e.g. GitHub? What's the purpose of supplying resolver to it?

**Comment by Sewer56** [comment]
> Again, what an amazing detailed analysis :)
> 
> One question, do you see `Onova.Difftool` as responsible also for uploading the diffs to e.g. GitHub? What's the purpose of supplying resolver to it?

I don't think the part of uploading the diffs should be the responsibility of an initial implementation of `Onova.Difftool`, only the creation of the artifacts. Maybe in the long run, such functionality could be implemented if *really necessary* but I truely believe that publishing diffs shouldn't be the responsibility of Onova but the user and their CI/CD solution,

Most CI/CD solutions already have very comprehensive deployment options, such as extremely popular AppVeyor.

![Appveyor Options](https://i.imgur.com/Lkr2NW6.png)

As for supplying the resolver, `Onova.Difftool` somehow needs to obtain the most recent version of the application to create a diff against. Most people probably do not configure their CI/CD solutions with persistent cached directories/files across builds and therefore would have to look into some other solution to do it.

The catch is, Onova (library) itself is perfect for this task. If the application is to be updated using Onova, then Onova already is able to download the latest version to update the application without any changes to the library. Since we are creating a new release to become the new latest version, it is only natural to download the current latest version to create a diff against as that will naturally become the 2nd latest version after the new build goes live.

-------------------

*One more thing to note.*

This is more of a thing to note in Onova documentation down the road if/once this is implemented.

If the CI/CD is building multiple configurations (e.g. Debug and Release), and the user is deploying Debug and Release builds to the same place, the Resolver may not know which build is the most recent Debug to diff against and which is the most recent Release to diff against.

This has an easy solution, which Onova already solves using the `fileNamePattern`.

The user in their CI/CD will have to put an `if` clause in the after build script where DiffTool would integrate to get the latest Debug to diff against when building Debug and latest Release to diff against when building Release. (i.e. Run the same DiffTool command but with a different `fileNamePattern` to distinguish latest Debug from Release)

In AppVeyor for example, this would be done as such (Batch/CMD syntax).

```
IF CONFIGURATION == Release
(
    // Create diff using DiffTool against latest Release version.
    ./Onova.Difftool.exe --resolver GithubPackageResolver --GithubPackageResolver.RepositoryOwner Tyrrrz --GithubPackageResolver.RepositoryName OnovaTestRepo --GithubPackageResolver.AssetNamePattern *-RELEASE.zip
)
ELSE
(
    // Create diff using DiffTool against latest Debug version.
    ./Onova.Difftool.exe --resolver GithubPackageResolver --GithubPackageResolver.RepositoryOwner Tyrrrz --GithubPackageResolver.RepositoryName OnovaTestRepo --GithubPackageResolver.AssetNamePattern *-DEBUG.zip
)
```

or in the case of the imaginary Github example from the last post

```
IF CONFIGURATION == Release
(
    ./Onova.Difftool.exe --resolver GithubPackageResolver --GithubPackageResolver.RepositoryOwner Tyrrrz --GithubPackageResolver.RepositoryName OnovaTestRepo --GithubPackageResolver.AssetNamePattern *.onv 
)

// Not publishing debug builds to Github releases.
```

(In AppVeyor `CONFIGURATION` is an auto assigned environment variable by the CD/CI of the currently building build configuration)

**Comment by Tyrrrz** [comment]
>As for supplying the resolver, Onova.Difftool somehow needs to obtain the most recent version of the application to create a diff against. Most people probably do not configure their CI/CD solutions with persistent cached directories/files across builds and therefore would have to look into some other solution to do it.

Right, makes sense.

>If the CI/CD is building multiple configurations (e.g. Debug and Release), and the user is deploying Debug and Release builds to the same place, the Resolver may not know which build is the most recent Debug to diff against and which is the most recent Release to diff against.

How often do people separately deploy different configurations of their builds? I only deploy RELEASE builds.

**Comment by Sewer56** [comment]
> How often do people separately deploy different configurations of their builds? I only deploy RELEASE builds.

I can't say since I don't yet specifically work in the industry. I would reckon that the answer is however a very, very small amount of people (probably mostly large businesses/development teams). I myself only deploy Release builds aswell.

What I do see very commonly though, and is something I do myself is publish both Release and Debug build artifacts on CI/CD. i.e. While I don't ship non-Release builds to users, I build as well as test both Release and Debug on AppVeyor and have artifacts published for both.

The specific case I was thinking about though was software supporting nightly builds, i.e. there is an update made available every day/every commit. If the nightly builds are e.g. only published on AppVeyor as artifacts and both Debug/Release are actively built there, we don't want to accidentally create a diff from Debug if someone is running a nightly Release build.

**Comment by Tyrrrz** [comment]
I see. I think it's fine if we assume people would only use Onova for their release builds.

**Comment by Tyrrrz** [comment]
Hi.
Unfortunately I have to descope this issue as the project has moved into maintenance mode, which means that new features are unlikely to get implemented.
