### ISSUE TITLE
Updater reuses the same hidden console window with the updatee when it restarts

### ISSUE THREAD

**Issue by Crydsch** [Tyrrrz/Onova#30]
I am using Onova with the WebPackageResolver with the ZipPackageExtractor.
Everything works fine, until the updater restarts my console application.
The process successfully starts, but the console window is not visible.

I am publishing the app as .net core 3.1 standalone package (win-64)

Is there something i can do?

**Comment by Tyrrrz** [comment]
It's probably related to #28. Does the app actually get updated?

**Comment by Crydsch** [comment]
Hey, thanks for the quick answer

I don't think its related. I do not use single exe files and it is getting updated correctly!
The sample app used for testing, prints the assembly version and if I start the app manually the window opens as expected and shows the new version.

**Comment by Tyrrrz** [comment]
I see, that's weird. Random guess - when the updater launches the updatee, it somehow ends up reusing the same console window (which was hidden because updater runs hidden). I don't know if it's possible though.

Update: looks like it's in fact what's happening.
https://stackoverflow.com/a/3634110/2205454
![image](https://user-images.githubusercontent.com/1935960/77566524-7399d080-6ece-11ea-9486-baf6be9d7291.png)

**Comment by Tyrrrz** [comment]
Apparently using `ShellExecute = true` should fix this issue.
https://github.com/dotnet/runtime/issues/22581

**Comment by Crydsch** [comment]
I see.

The updater does use `UseShellExecute = false`.
I am not sure what this option does, surely there was a good reason to set it that way.

Maybe there should be a way to specify that the updatee is a console application and to use ´UseShellExecute = true´

**IF** this is the issue after all...

**Comment by Tyrrrz** [comment]
I'm about 99% sure this is the issue. Can't really test right now though.

`UseShellExecute = true` instructs the OS to execute a process via a shell instead of doing it directly. For example, you can't execute a `txt` file per se (because it's not executable) but with shell execute you can, it will run it through shell which will open it in default text editing application. It has a bunch of other side-effects and implications as well, but I think it should be okay for our case.

I will look into this and other reported issues in a week or two, when I have more time. If you have time, I'll be happy if you submit a PR. I expect one test to break because of it though.

**Comment by Crydsch** [comment]
Update:
I just tested it and this is in fact the problem.
Using `UseShellExecute = true` fixes the problem.
