### ISSUE TITLE
Version 2.6.8 does not work

### ISSUE THREAD

**Issue by doylecnn** [Tyrrrz/Onova#53]
### Version

2.6.8

### Details

I was using Onova 2.6.7 with no issues, but after upgrading to 2.6.8 I am experiencing a problem.

The issue is:

I can see through Windows Task Manager that {appname}.Update.exe launched, indicating the update started.

However, {appname}.Update.exe disappeared quickly, showing the update ended.

But Onova did not automatically restart, and the version also did not update.

When I manually double click to launch Onova, the version number is still the old one, the update was not successful.

I hope you can investigate this issue and find out possible reasons. Currently it seems like the update process for 2.6.8 has some problems.

Thank you for providing the great Onova app, I hope this bug can be fixed to let the update work smoothly again.

### Steps to reproduce

1. I packaged App.exe, with AssemblyVersion = 1.0.0.0, into App-v1.0.zip
2. I packaged App.exe, with AssemblyVersion = 2.0.0.0, into App-v2.0.zip
3. I launched App.exe of v1.0 and it detected an update, prompting me to update
4. I closed the program, and through Windows Task Manager I saw the App.Update.exe process
5. The App.Update.exe process ended, but it did not restart App.exe
6. When I double clicked App.exe again it again prompted me of an update, and checking the exe's AssemblyVersion it was still 1.0.0.0

The issue here seems to be that although the updater process (App.Update.exe) runs, it is not actually performing the update and replacing the older App.exe with the new version. So when the updater process ends, the old App.exe is still there and runs as normal.

**Comment by Tyrrrz** [comment]
Hi.

Can you check the logs in `%localappdata%/Onova/[Your App]/Log.txt`?

**Comment by doylecnn** [comment]
Onova 2.6.8, Log.txt:

> 29-May-2023 10:35:07.490> Onova Updater v2.6.8.0 started with the following arguments:
> - UpdateeFilePath = C:\temp\ps2kbemu\app.exe
> - PackageContentDirPath = C:\Users\xxx\AppData\Local\Onova\app\0.0.1.7
> - RestartUpdatee = True
> - RoutedArgs = 
> 29-May-2023 10:35:07.498> Locking the updatee directory...
> 29-May-2023 10:35:12.545> System.ComponentModel.Win32Exception (0x80004005): Another program is using this file, and the process cannot access it.
>    in Onova.Updater.Utils.DirectoryEx.Lock(String dirPath, FileAccess access, FileShare share)
>    in Onova.Updater.Updater.AcquireLock()
>    in Onova.Updater.Updater.Run()


Onova 2.6.7, Log.txt:

> 29-5月-2023 10:47:03.755> Onova Updater v2.6.7.0 started with the following arguments:
>   UpdateeFilePath = C:\temp\ps2kbemu\app.exe
>   PackageContentDirPath = C:\Users\xxx\AppData\Local\Onova\app\0.0.1.7
>   RestartUpdatee = True
>   RoutedArgs = 
> 29-5月-2023 10:47:03.765> Waiting for all running updatee instances to exit...
> 29-5月-2023 10:47:03.765> Copying package contents from storage to updatee's directory...
> 29-5月-2023 10:47:03.781> Restarting updatee [C:\temp\ps2kbemu\app.exe ]...
> 29-5月-2023 10:47:03.873> Restarted as pid:29448.
> 29-5月-2023 10:47:03.873> Deleting package contents from storage...


the WPF App.xaml.cs code:
```csharp
public partial class App: Application {
    protected override async void OnStartup(StartupEventArgs e) {
        await CheckUpdate();
    }

    private async Task CheckUpdate() {
        using IUpdateManager _updateManager = new UpdateManager(
            new LocalPackageResolver(Internal.Config.RepositoryDirPath, "app-v*.zip"),
            new ZipPackageExtractor());

        var check = await _updateManager.CheckForUpdatesAsync();

        if (check.CanUpdate) {
            await _updateManager.PrepareUpdateAsync(check!.LastVersion!);
            MessageBox.Show("app will be update and restart.");

            _updateManager.LaunchUpdater(check!.LastVersion!, true);
            this.Shutdown();
        }
    }
}
```

**Comment by Tyrrrz** [comment]
Thank you for the log. It looks like it could not acquire a lock on the app directory.

The difference between 2.6.7 and 2.6.8 is that the older versions of Onova only tried to acquire a lock on the updatee assembly (i.e. `.exe` or `.dll` file). That sometimes lead to issues where some other files failed to overwrite, and the update became corrupted. Locking the entire directory was meant to resolve that issue.

> I can see through Windows Task Manager that {appname}.Update.exe launched, indicating the update started.
> However, {appname}.Update.exe disappeared quickly, showing the update ended.

This is weird, because the updater should retry at least 5 times, for a total of 5 seconds, when acquiring the lock:

https://github.com/Tyrrrz/Onova/blob/a00274f3f88ba9119b1693caaa18f77deb8522ef/Onova.Updater/Updater.cs#L44-L59

In any case, can you please try reproducing the issue again, but this time checking which process has a lock on your app's directory or one of its files?

You can see all resource handles in Resource Monitor (`Win+R` → `resmon` → `Enter`) if you click on the _CPU_ tab and then search for the directory name in the _Associated Handles_ panel:

![image](https://github.com/Tyrrrz/Onova/assets/1935960/27eeef18-678d-4bee-849b-a8ad07df916a)

**Comment by doylecnn** [comment]
I created a minimal reproducible [wpf project](https://github.com/doylecnn/Wpf-Onova-Test) , and recorded a sample video [Onova 2.6.8 test.mp4](https://github.com/doylecnn/Wpf-Onova-Test/blob/main/Onova%202.6.8%20test.mp4) to demonstrate the problem I encountered with Onova in my project.

In the project,

By modifying the TextBlock in Wpf-Onova-Test/MainWindow.xaml to display the version.

By modifying the ninth line of the csproj file, modify the version of the generated assembly.

Lines 16 to 23 in the csproj file are used to automatically compress to the specified directory, and the directory is associated with the directory checked for updates in Wpf-Onova-Test/App.xaml.cs.

As a complete reference, I also uploaded the publish settings file (path: Wpf-Onova-Test/Properties/PublishProfiles/FolderProfile.pubxml)

Thank you for your help so far. I look forward to working together to resolve this issue.

**Comment by Tyrrrz** [comment]
Thank you very much for a detailed report and reproduction @doylecnn!

It seems that the issue was that the application directory was locked for read by File Explorer, which prevented Onova from doing the same. I came to the conclusion that directory locking is not an optimal solution and replaced it with individual locks for each copied file.
